### ISSUE TITLE
[Feature request]  - Show server starts, stops and crashes in discord

### ISSUE THREAD

**Issue by ProsperCraft** [Denis3d/Minecraft2Discord#1]
topic says it all.

**Comment by Denis3d** [comment]
Thanks for your suggestions ! I will add this in 1.0.1.
Denis

**Comment by Denis3d** [comment]
Minecraft2Discord 1.0.1 released with many new features. Server crash (sended as server stop) isn't working as well. Will be improved for next version!
If you have any other suggestion, feel free to open a new issues.
