### ISSUE TITLE
[1.14.4] Feature request- Crash detection and announcement in discord.

### ISSUE THREAD

**Issue by ProsperCraft** [Denis3d/Minecraft2Discord#11]
Would be great if when the server crashes it would announce it in discord.

**Comment by 4rz0** [comment]
If the server crashes, mods can't do things anymore, so this is not possible.

**Comment by ProsperCraft** [comment]
Instead of printing server closed in discord, print - Server crash detected

**Comment by Denis3d** [comment]
Server crash is a bit hard to detect while the mod will no longer respond after the crash.
I have no idea how to do that without killing server performance.

**Comment by Darkere** [comment]
Looks like discordintegration does this by checking both ServerStopping and ServerStopped events

https://github.com/Chikachi/DiscordIntegrationCore/blob/2ecff7707c733df9cf5f54c9f259cabbc0db5b72/src/main/java/chikachi/discord/core/Proxy.java#L74

**Comment by ProsperCraft** [comment]
Thank you, that is the one we use in 1.12.2
