### ISSUE TITLE
Allow roles to select who has access to commands

### ISSUE THREAD

**Issue by Darkere** [Denis3d/Minecraft2Discord#12]
Having access to commands is amazing, however adding all 20 people that should have access by name is a pain. Any chance that we can allow people with specific roles access to commands?

**Comment by Denis3d** [comment]
Thanks for your suggestion,
Make command accessible from discord role shouldn't be hard. 
I will add this in the next update that I will make when back from holiday.

**Comment by Denis3d** [comment]
Added in 1.0.5
