### ISSUE TITLE
Respond to failed commands

### ISSUE THREAD

**Issue by Darkere** [Denis3d/Minecraft2Discord#14]
Commands with typos right now spit out a stack trace on the console. It would be nice to be able to see an error or something in discord instead.

Some command outputs like for /say also don't appear in discord for some reason.

**Comment by Denis3d** [comment]
Thanks for your issues. 
Indeed command error messages isn't send because it is empty message. I will investigate further tomorrow.
/Say command dosent return the messages on discord because the chat message event isn't triggered. I will fix this in the next update.

**Comment by Denis3d** [comment]
Fix on 1.0.6
