### ISSUE TITLE
Crash on advancement

### ISSUE THREAD

**Issue by Darkere** [Denis3d/Minecraft2Discord#15]
https://hatebin.com/pklfhoytqo

the player was saying it was the Acquiring Hardware advancement but I don't think that's actually relevant. The game was running fine (with advancements in discord) for days before this. 

Note we were still on 1.0.5.

**Comment by Denis3d** [comment]
Thanks for reporting.
I just launch a server to reproduce this bug and I didn't get any problem with this advancement.
Can you describe the step to reproduce and/or send your config file after removing your bot token ?
Denis

**Comment by Darkere** [comment]
ok, so when in testing just now I've found that advancements seem quite a bit buggy on our server for some reason. 
Was hoping the actual problem would be easily visible but from looking at the code it's not quite that obvious. 
There have been lot's of advancements without a crash by now so I'm hoping it's just a very rare case. Will be back if it's happens more often :)

Config in case it's still relevant: https://pastebin.com/kehMvLSF

**Comment by Denis3d** [comment]
After reading my code again because of issue #16 I notice that I make a bug fix in 1.0.6.
Perhaps the bug was coming of that. If you still experience crash in 1.0.5 please update to the last version

**Comment by IchigoGames** [comment]
Still happening in 1.0.6

**Comment by IchigoGames** [comment]
https://pastebin.com/buUrezE5  java.lang.NullPointerException: Ticking entity
    at ml.denis3d.minecraft2discord.BotEvents.onAdvancement(BotEvents.java:103) ~[?:1.14.4-1.0.6] {}
