### ISSUE TITLE
[1.14.4] Server crash with minecraft2discord-1.14.4-1.0.7 - ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by ProsperCraft** [Denis3d/Minecraft2Discord#17]
https://gist.github.com/ProsperCraft/c78bc8216efd0400e6bd14ee9fcbf180

ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

This happened right after I wiped my configs folder on the dedicated server.
[debug.log](https://github.com/Denis3d/Minecraft2Discord/files/3614608/debug.log)
[latest.log](https://github.com/Denis3d/Minecraft2Discord/files/3614609/latest.log)

**Comment by Denis3d** [comment]
Seem to be a forge issue... That have been resolved earlier this month... I will contact the forge team..

**Comment by Denis3d** [comment]
Fixed in 1.0.8
