### ISSUE TITLE
Crash when logging into Client - Missing Permission: MESSAGE_WRITE

### ISSUE THREAD

**Issue by Saiyaken-PHOENIX** [Denis3d/Minecraft2Discord#19]
I've recently placed this mod on my testout Minecraft server.  it completely crashes the server every time I log into it from client, and every time I check it gives me some missing permission: message_write in the logs and the terminal.  I've already given the bot writing permissions on Discord.  I'm stumped on what to to tbh.

[crash-2019-09-18_14.35.01-server.txt](https://github.com/Denis3d/Minecraft2Discord/files/3627921/crash-2019-09-18_14.35.01-server.txt)

**Comment by Denis3d** [comment]
As say in the log your bot is missing permission. Perhaps have you enabled the wrong one ?
You can try to give the bot admin permission and try again. If you still have crash there is a problem with the mod. If you have no more issue you need to recheck your bot permission in your guild.
Denis

**Comment by Saiyaken-PHOENIX** [comment]
> 
> 
> As say in the log your bot is missing permission. Perhaps have you enabled the wrong one ?
> You can try to give the bot admin permission and try again. If you still have crash there is a problem with the mod. If you have no more issue you need to recheck your bot permission in your guild.
> Denis

It now works after giving the bot admin privileges.  Before it never sent a message to the Discord server, now it does.    Though I am worried about giving any bot admin privileges, is there any specific ones that it needs?  Also, do I have to run multiple bots if I have multiple servers that needs to be integrated, or can I just run the plugin with the same credentials for the bot and use different channels to output?  
Currently testing some more things out while the bot is working, thanks.

**Comment by Denis3d** [comment]
The bot need the read message, send/write messages and manage webhooks. It's the second one who is missing on the crash you send. You can add many server on the same bot but if you send message on the same channel the message send from the bot account by the first server will not be send to the second one and vice versa. While it's just an account you can connect multiple time at once. So there is no problep with different channels.
