### ISSUE TITLE
[Feature request] Add a way for other mods to relay messages

### ISSUE THREAD

**Issue by 4rz0** [Denis3d/Minecraft2Discord#2]
The title pretty much says it.
Something like forge's IMC would be useful for other mods to send their own messages to Discord through this mod.
This could for example be used by Questing mods (FTB Quests, BetterQuesting) to relay their own advancements to Discord.

**Comment by Denis3d** [comment]
Hi, thanks for your suggestion. Using IPC to send message is a very good idea. I will implement that in the next update!
For questing mod, the message will be send like minecraft advancement if the minecraft advancement event is called... But if it isn't mod will be able to send the message using this awesome feature
Denis

**Comment by Denis3d** [comment]
Added in 1.0.2 ! If you have any other suggestion, feel free to open a new issue.
