### ISSUE TITLE
Allow certain commands for regular players

### ISSUE THREAD

**Issue by Darkere** [Denis3d/Minecraft2Discord#20]
There are a couple of commands (like /list and /forge tps and more) where would be nice if they were also available to regular players. 

The discord presence can show the number of players online but clicking the bots name (especially if the last bot message is further up) is fairly unintuitive and also doesn't show who is online.

**Comment by Denis3d** [comment]
How would you like I implement that? Would you like I make a list of command that is allowed? Use the minecraft permission level to select allowed command?
I think if I use the last command it will allow player to get kit,... While offline

**Comment by Darkere** [comment]
I think a configurable list with some defaults makes the most sense. 

As much as mod devs are amazing, I don't trust them to always setup permission levels correctly. At least not with how difficult making commands has gotten in 1.14. 

Also in the future, there may be more commands that could be allowed for players. Like a clear inventory command that they could use to stop themselves from crashing.

**Comment by Denis3d** [comment]
Would you like I set a message when you aren't allowed to use a command or just don't awnser ? 

This is whithout my id in the config file. Just the "/discord" command name :
![image](https://user-images.githubusercontent.com/35769613/65371908-8d790300-dc60-11e9-8c71-d26bce64c259.png)

**Comment by Darkere** [comment]
That is a difficult question. No answer is just bad IMO but answering every command attempt can spam the chat pretty quickly. 

I think the best way of going about it is answering with something like:  
"You don't have permission to use this command. Use /commands to see which commands you have access to". 

And then ofc that second command that posts a list of the allowed commands (with special cases for operators lol).

**Comment by Denis3d** [comment]
Perhaps can I override the help command while it will print every command if you allow it.
Then i can ad inside every cammand allowed in the config

**Comment by Denis3d** [comment]
Added in 1.1.0 who is available on curseforge...
Sorry for the late update
