### ISSUE TITLE
Format error response

### ISSUE THREAD

**Issue by Darkere** [Denis3d/Minecraft2Discord#21]
The Minecraft command errors are already pretty terrible but usually, you can at least infer what they mean. 

Would be nice if they were readable 😉 
![image](https://user-images.githubusercontent.com/4283717/65270811-379b4280-db1c-11e9-8053-2de4860eb200.png)

**Comment by Denis3d** [comment]
That's the minecraft color langage I think I have remove it 🤔 I will look in the code tonight.

**Comment by Denis3d** [comment]
One wich version are you ?
I think I fix that in 1.0.6...

**Comment by Darkere** [comment]
Oh, I probably should've checked with the latest version first. My Bad.
