### ISSUE TITLE
Bot does not relay messages from other discord bots to in game.

### ISSUE THREAD

**Issue by Electrofried** [Denis3d/Minecraft2Discord#22]
Can you please add a config option to allow the bot to relay messages from other bots to minecraft? Right now it seems to just discard any messages from bots.

**Comment by Denis3d** [comment]
Indeed, bot message isn't related... I can disable this of course. I just have to make sur it will not relay the message it send too :smile:

**Comment by Denis3d** [comment]
Fixed in 1.1.0 who is available on curseforge. 
PS : Sorry for the late update
