### ISSUE TITLE
[1.14.4] Spam from Bot w/ Sleeping Advancement

### ISSUE THREAD

**Issue by oitsjustjose** [Denis3d/Minecraft2Discord#25]
## Software Versions
- `Minecraft 1.14.4`
- `Forge 28.1.61`
- `MC2Discord 1.1.0`

## Issue Overview

I was testing on the Geolosys Testing Server (which I run) and wanted to use this mod. As soon as I slept, this was spammed in our chat until I stopped the server:

![](https://i.imgur.com/qK0ckZZ.png)

## Other Details

I have no idea if I've done something wrong or not, but I had to go and disable the advancements feature for now. It could be a data pack we're using for multiplayer sleep (1 player is enough to make it day -- it's not a mod but a vanilla data pack that may be firing the advancement repetitively??). I can do further testing if necessary.

## Proposed Solution

Regardless if it's a mod compatibility/conflict issue or not, it should probably be filtered to for the connector to *not* send an incoming message to Discord if the message is the same as the last message and it's been `x` seconds since that last message was sent.

**Comment by Denis3d** [comment]
Hi,
I add in the first or second update of M2D a way to avoid some advancement to be send while some data pack like multiplayer_sleep or vanilla recipe avancement were spamming. In the config you can find a field called "hideAdvancementList" and set it as : ["multiplayer_sleep"] and the advancement from this data pack will not be sent anymore
Denis

**Comment by Denis3d** [comment]
Ps : can you close the issue if your problem is resolved?
Thanks in advance 
Denis
