### ISSUE TITLE
Is there a way to mention people via MC to Discord and trigger mention in Discord?

### ISSUE THREAD

**Issue by fuzzyweapon** [Denis3d/Minecraft2Discord#26]
Wondering if there's a way to @mention in MC and have it trigger in Discord.  We tried full @discordName#12345 style, but this didn't seem to work.

**Comment by Denis3d** [comment]
The syntax is <@discordId>. You can get it by @mention someone and adding a \ before sending the message : \@mention.
Is this what you want?

**Comment by Denis3d** [comment]
Ps: for roles it is <@&roleId>

**Comment by Denis3d** [comment]
If this resolved your issue can you please close it. Else can you describe what still dosent work?
Thanks
Denis

**Comment by Denis3d** [comment]
Closed while there is no response...
