### ISSUE TITLE
IllegalStateException crash: Cannot get reference as it has already been Garbage Collected

### ISSUE THREAD

**Issue by Corosauce** [Denis3d/Minecraft2Discord#27]
I wasn't around when it happened, but after asking the couple people that were on the server it doesn't sound like they were doing much when it crashed, they were booted from the server, they hadn't gone to disconnect themeslves.

crash report: [https://gist.github.com/Corosauce/b9b71b42be689b7763919a9be282d68d](https://gist.github.com/Corosauce/b9b71b42be689b7763919a9be282d68d)

Edit: From discussion with another dev sounds like its due to lazy unreliable design in JDA itself. Damn.

**Comment by Denis3d** [comment]
As you say it come from a crash of jda itself. But you can update M2D in 1.1.0 while this version use jda 4 while version 1.0.x use jda 3. Perhaps the rewrite of library has solved this problem.
Ps : if your issue is resolved can you closed it please?
