### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Darkere** [Denis3d/Minecraft2Discord#28]
Not entirely sure what is causing this but there is a lot of it. 
![image](https://user-images.githubusercontent.com/4283717/71088561-feb44d80-219e-11ea-9f0c-67dae31d230b.png)

version: 1.14.4 1.1.0

**Comment by Denis3d** [comment]
Must be fix in 1.1.0 (for both mc 1.14.4 and mc 1.15.1). Please reopen if not.
Denis
