### ISSUE TITLE
[1.14.4] Language Provider Startup Crash on Forge 28.1.109

### ISSUE THREAD

**Issue by VarvatosVex** [Denis3d/Minecraft2Discord#29]
**Note: This happened as the mod was added to the modpack Enigmatica 4 (v0.4.4).
I cannot be sure it's not a mod incompatibility issue, but based on the error I assume it's more of a forge issue than some other mod throwing a fit.**

Pertinent error message:
> net.minecraftforge.fml.ModLoadingException: Mod File minecraft2discord-1.14.4-1.1.1.jar needs language provider javafml:29 or above to load
§7We have found 28.1

Full **latest.log** can be found at:
https://gist.github.com/VarvatosVex/6fac0a50ec14339bc4582e8d7a08ca5a

Forge version used:
**forge-1.14.4-28.1.109.jar**

Mod version used:
**minecraft2discord-1.14.4-1.1.1.jar**

Problem Description:
Server crashes on startup when the mod is added.
When the mod is removed the server starts up perfectly fine.
It seems to be an incompatibility with the version of forge used, but it's specified that the mod supports 28.1.X which is the version I'm using.
Maybe an oopsie happened in mod version 1.1.0 -> 1.1.1?

**Comment by Denis3d** [comment]
Seem indeed to be a mistake... Thanks for reporting.
I uploaded a working version on curseforge that should appear soon.
Sorry for the inconvenance
