### ISSUE TITLE
Random System Out Print

### ISSUE THREAD

**Issue by cjm721** [Denis3d/Minecraft2Discord#3]
Don't think this was intended to be left in.

https://github.com/Denis3d/Minecraft2Discord/blob/c6a1729fa468641c30fb12b2be54d8a8d39e0fbc/src/main/java/ml/denis3d/minecraft2discord/BotEvents.java#L98

**Comment by Denis3d** [comment]
Yes, indeed I will remove this mistake in the next update.
Thanks for reporting.
