### ISSUE TITLE
Handle Emojis

### ISSUE THREAD

**Issue by Darkere** [Denis3d/Minecraft2Discord#30]
Discord emojis currently appear as ▌▌ in-game. 

I don't know how possible it is to display the discord emojis ingame but that would be the ideal solution.

I would be fine with `:emojiname:` too.

**Comment by Denis3d** [comment]
I never tested with emoji but seem logic that emoji aren't properly displayed. I will try to handle emoji when back from Hollydays

**Comment by Denis3d** [comment]
Custom discord emote was already well displayed. Other emoji was supposed to be rendered as classic characters that is apparently not well supported by the minecraft chat. It will now be replaced by the :emoji_name: format. The update will be released in a few days on curseforge.
