### ISSUE TITLE
Don't display Invisible Advancements

### ISSUE THREAD

**Issue by Darkere** [Denis3d/Minecraft2Discord#31]
From a quick look at the advancement code, it seems like `Advancement.getDisplay() == null` gives an easy way to see if the advancement is supposed to be invisble. 

Being able to block some other advancements is still useful though as some mods like to go overboard with the number of advancements they add.

**Comment by Denis3d** [comment]
Okey I will look into it
Thanks

**Comment by Denis3d** [comment]
It's done . It will be available on curseforge in a few days
