### ISSUE TITLE
[1.15.2] NPE on closing the server.

### ISSUE THREAD

**Issue by ProsperCraft** [Denis3d/Minecraft2Discord#32]
https://gist.github.com/ProsperCraft/bd96af3847b8bda17f84c4b90ae559d9

minecraft2discord-1.15.2-1.1.3.jar

java.lang.NullPointerException
        at ml.denis3d.minecraft2discord.Minecraft2Discord.onServerStopped

This was a fresh config, on its first run, I had just installed the mod, and was shutting down to edit the config.

**Comment by Denis3d** [comment]
Okey I think I see from where is coming the problem. I will push a fix in the next update. Should be resolved when you put a working token

**Comment by Denis3d** [comment]
Should be fix on the next update.
