### ISSUE TITLE
this mod keeps server from stoping

### ISSUE THREAD

**Issue by IchigoGames** [Denis3d/Minecraft2Discord#37]
I believe this issue is very similar to a issue i had in the past with https://github.com/Szewek/Flux/issues/22 after they fixed this at first everything was ok but then it stopped working again i thought it was the same mod again but but they said it was fixed yesterday when i updated my server i noticed it stopped like it should did not freeze on saving like it normally does the only deference was i had not added my add on mods to server yet only got 2 of them world edit and this mod after testing both it turns out this mod is the reason for server not coming to a stop when given stop command.

this time i let it sit there and try to stop it did stop 3 minutes after chunks where saved

Minecraft 1.15.2
minecraft2discord-1.15.2-1.1.5
Forge 31.1.77

[crash-2020-05-12_07.27.10-server.txt](https://github.com/Denis3d/Minecraft2Discord/files/4616679/crash-2020-05-12_07.27.10-server.txt)
![Capture](https://user-images.githubusercontent.com/11888162/81715590-03271e80-943e-11ea-8e48-3422beb64f3c.PNG)

**Comment by IchigoGames** [comment]
without this mod it stops pretty much instantly after clicking stop

**Comment by Denis3d** [comment]
Perhaps the bot not completly shuting down
I will look into that

**Comment by Denis3d** [comment]
Should be fixed in 1.1.6
Reopen if you still have the bug
Denis

**Comment by IchigoGames** [comment]
sorry about this i was taking a brake from minecraft i just started up a server on my pack and tested with and without this mod and its still keeping it from stoping.

**Comment by IchigoGames** [comment]
you want me to make a new issue or reopen this one ?

**Comment by Denis3d** [comment]
Is it a duplicate with #38 that just get opened ? If yes we will use the new one else you can reopen this one
