### ISSUE TITLE
Option for OP's to send commands from discord

### ISSUE THREAD

**Issue by Darkere** [Denis3d/Minecraft2Discord#4]
We are now running your mod on our 1.14 playthrough and its working great (apart from datapacks spamming hidden advancements...).

But one of the features we are missing is being able to send commands to the server via discord. We very often used this for whitelisting more players or profiling without having to join the server/opening up the server console.

**Comment by 4rz0** [comment]
I second this request.
I suggest looking at the way it's done in [Chikachi's DiscordIntegration mod](https://github.com/Chikachi/DiscordIntegration).
There's a list of Discord user IDs allowed to use commands in the config. For each user, you can add a command that discord listenes to and another command that's then sent to the server.

**Comment by Denis3d** [comment]
Thanks for the idea. I will look for this awesome feature as soon as possible.
Is it vanilla advancement or only added advancement which spam hidden advancement ?
Perhaps could you give me the name of the data pack? So I can add a config field to block some mods advancement.

**Comment by Darkere** [comment]
The problematic one was from the Multiplayer sleep Datapack. I think we got it from here: https://vanillatweaks.net/picker/datapacks/ . 

It spammed
`kjmaster1 has made the advancement multiplayer_sleep:sleep.`
about 100 times.

**Comment by Denis3d** [comment]
Everything added in 1.0.3. 
Feel free to update by downloading the mod in curseforge.
If you have new features idea or if you find some bug open a new issues :+1:
