### ISSUE TITLE
[1.16.1] Error when bot logged in.

### ISSUE THREAD

**Issue by Gbergz** [Denis3d/Minecraft2Discord#42]
Title^

Error in console:
https://hatebin.com/utbdjgzius

**Forge:** 32.0.75
**MC:** 1.16.1
**M2D Version:** 2.0.2

Anything to worry about?
**-** Gbergz

**Comment by Denis3d** [comment]
Nothing to worry about indeed... Just the global_unique_player variable that isn't working. Darkere fixed it in a PR but I have no computer to accept it for now
Thanks for reporting
