### ISSUE TITLE
Missed Heartbeats, large lag spike

### ISSUE THREAD

**Issue by Lughbaloo** [Denis3d/Minecraft2Discord#43]
Not entirely sure what causes this. Had a lag spike in-game that causes several players to time out and disconnect. Didn't crash the server however. Only happened once so far, will report if it happens again.

Currently installed in a Valhelsia 2 server.
Attached is the config.
[minecraft2discord.txt](https://github.com/Denis3d/Minecraft2Discord/files/5179110/minecraft2discord.txt)

Error message:
[JDA Gateway-Worker 1/INFO] [STDERR/]: [ml.denisd3d.repack.org.slf4j.impl.SimpleLogger:write:318]: [JDA Gateway-Worker 1] WARN ml.denisd3d.repack.net.dv8tion.jda.internal.requests.WebSocketClient - Missed 2 heartbeats! Trying to reconnect...

**Comment by Denis3d** [comment]
Really sorry i haven't recevied an notification for the issue and I just saw it -_-
This error message means that the discord bot that is running inside the minecraft server just got the same problem as your player who disconected : a too long time without response from the server / code execution. This means that the server get a lag spike and the discord bot get disconected a few seconds before reconecting
IDK if it was clear :) 
Denis
