### ISSUE TITLE
Unable to send from Game to Discord

### ISSUE THREAD

**Issue by shenniko** [Denis3d/Minecraft2Discord#44]
Hi, first time using this mod.

Having issues sending anything from game to Discord, but sending from Discord to Game works fine.

So when i join game, it doesnt display in discord that ive joned (though does show on the Bot (playing 1/20 players)
Same as when i leave, it doesnt post into the chat ive specified.

When chatting in game, it doesnt send it to discord chat window.
When chatting in discord chat, it DOES send it to game.

Any ideas where im going wrong?

**Comment by Denis3d** [comment]
Perhaps an issue with your discord bot permission. It needs manage webhook permission to send message on discord. If it's the case you should have an error message in your console
Denis

**Comment by shenniko** [comment]
Re-boot of my server.. and its all working now.. :)
