### ISSUE TITLE
[1.14.4] Please update to forge .45 It has breaking changes.

### ISSUE THREAD

**Issue by ProsperCraft** [Denis3d/Minecraft2Discord#7]
.45 introduced some breaking changes and most mods need to update.

I suspect M2D needs to as well because when added it seems to block other mods from registering.  

Log below-
I took a known good loading world, and added M2D and it failed to load properly.

[debug.log](https://github.com/Denis3d/Minecraft2Discord/files/3487111/debug.log)
[latest.log](https://github.com/Denis3d/Minecraft2Discord/files/3487112/latest.log)

**Comment by Denis3d** [comment]
Thanks for reporting. I just upload a new version on M2D curseforge page.
