### ISSUE TITLE
[1.14.4] The update today requires 1.14.3 

### ISSUE THREAD

**Issue by ProsperCraft** [Denis3d/Minecraft2Discord#8]
Please update, and increment the version number.

![af9fa728f4ddb063a400e175e6d3a615](https://user-images.githubusercontent.com/4427684/62815553-84303e80-bad7-11e9-99de-8184287c6015.png)

**Comment by jakey1995abc** [comment]
Same issue here.

**Comment by Denis3d** [comment]
Sorry I made a mistake updating the mod. I'm deploying a new version on curseforge...
To avoid any conflict with previous version I change the mod version to 1.0.4 and I will delete the yesterday update.
