### ISSUE TITLE
[1.14.4] Stacktrace on console when rebooting server. java.lang.NullPointerException

### ISSUE THREAD

**Issue by ProsperCraft** [Denis3d/Minecraft2Discord#9]
https://gist.github.com/ProsperCraft/ac8fa10a48931ccbb3ca3dde0a843f4e

	minecraft2discord-1.14.4-1.0.4.jar

**Comment by Denis3d** [comment]
Seem to be due to the bot who log out after the server stop the server chat. A message send between this two shutdown step will result to this crash.
I will move earlier the bot logout in the next update.
This bug isnt major, he occure sometimes when shutting down the server.
Thanks for reporting

**Comment by Denis3d** [comment]
Should be fixed in 1.0.5
